"""

    llm-qlient • Qt desktop client for interacting with local LLMs

    This file is a part of the llm-qlient
    project and distributed under MIT license.

    Repository: https://github.com/kadir014/llm-qlient
    Issues:     https://github.com/kadir014/llm-qlient/issues

"""

from typing import Any

from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum, auto
from time import time
import uuid

from PyQt6.QtGui import QIcon, QPixmap

from llm_qlient import shared
from llm_qlient.core import log
from llm_qlient.core.types import JSONContent
from llm_qlient.ui.pages.base_view import BaseView


class Serializable(ABC):
    """
    Base protocol for serializable dataclasses.
    """

    @abstractmethod
    def serialize(self) -> JSONContent:
        ...

    @classmethod
    @abstractmethod
    def deserialize(cls, data: JSONContent) -> "Serializable":
        ...


def immutable_fields(*field_names: str):
    """
    Make certain fields immutable for a dataclass.

    This relies on `hasattr`, so assignment at initialization is allowed
    but reassignment after is not allowed.

    Parameters
    ----------
    field_names
        Names of the dataclass fields to make immutable
    """

    def wrapper(cls):
        original_setattr = cls.__setattr__

        def __setattr__(self, name: str, value: Any) -> None:
            if name in field_names and hasattr(self, name):
                raise AttributeError(f"{name} is immutable")
            original_setattr(self, name, value)

        cls.__setattr__ = __setattr__
        return cls

    return wrapper


@immutable_fields("id")
@dataclass
class Page:
    """
    Content page.

    Attributes
    ----------
    id
        Internal module representation
    name
        Display name
        Inferred from id if not given
    icon
        Themeable icon name or QIcon instance
    view
        Attached UI view
    """

    id: str
    icon: str | QIcon | None = None
    name: str = ""
    view: BaseView | None = None

    def __post_init__(self) -> None:
        if not self.name:
            self.name = self.id.capitalize()

    def __eq__(self, other: Any) -> bool:
       return isinstance(other, Page) and self.id == other.id

    def __hash__(self) -> int:
        return hash(self.id)
    

@immutable_fields("ui_name")
@dataclass
class UserPersona(Serializable):
    ui_name: str
    name: str
    avatar_path: str
    personality: str
    avatar_pixmap: QPixmap | None = None

    def serialize(self) -> JSONContent:
        return {
            "ui_name": self.ui_name,
            "name": self.name,
            "avatar_path": self.avatar_path,
            "personality": self.personality
        }
    
    @classmethod
    def deserialize(cls, data: JSONContent) -> "UserPersona":
        return cls(
            ui_name=data["ui_name"],
            name=data["name"],
            avatar_path=data["avatar_path"],
            personality=data["personality"]
        )
    

@immutable_fields("ui_name")
@dataclass
class Character(Serializable):
    """
    Definition and personality of the AI assistant represented by the LLM.

    Attributes
    ----------
    ui_name
        Unique name of the character used as an identifier and displayed on UI
    name
        Name of the character given in the prompt
    avatar_path
        Path to avatar image of character
    system_prompt
        System prompt sent to final chat completion
    personality
        Personality description of the character
    opening_message
        Message content if character sends the first message
    """

    ui_name: str
    name: str
    avatar_path: str
    system_prompt: str
    personality: str
    opening_message: str
    avatar_pixmap: QPixmap | None = None

    def serialize(self) -> JSONContent:
        return {
            "ui_name": self.ui_name,
            "name": self.name,
            "avatar_path": self.avatar_path,
            "system_prompt": self.system_prompt,
            "personality": self.personality,
            "opening_message": self.opening_message
        }
    
    @classmethod
    def deserialize(cls, data: JSONContent) -> "Character":
        return cls(
            ui_name=data["ui_name"],
            name=data["name"],
            avatar_path=data["avatar_path"],
            system_prompt=data["system_prompt"],
            personality=data["personality"],
            opening_message=data["opening_message"]
        )


class ConversationRole(Enum):
    """
    Author of chat message.

    Attributes
    ----------
    ASSISTANT
        Message is generated by LLM
    USER
        Message is written by user
    """
    ASSISTANT = auto()
    USER = auto()

@immutable_fields("id")
@dataclass
class ConversationMessage(Serializable):
    """
    Single text chat conversation message.

    Attributes
    ----------
    id
        Immutable, unique identifier
    role
        Author of the message
    content
        Text content of the message
    timestamp
        Unix timestamp of creation of the message
    """    

    role: ConversationRole
    content: str
    timestamp: float

    def __post_init__(self) -> None:
        self.id = str(uuid.uuid4())

    def __eq__(self, other: Any) -> bool:
       return isinstance(other, ConversationMessage) and self.id == other.id

    def __hash__(self) -> int:
        return hash(self.id)
    
    def serialize(self) -> JSONContent:
        return {
            "role": self.role.name,
            "content": self.content,
            "timestamp": self.timestamp
        }
    
    @classmethod
    def deserialize(cls, data: JSONContent) -> "ConversationMessage":
        return cls(
            role=ConversationRole[data["role"].upper()],
            content=data["content"],
            timestamp=data["timestamp"]
        )

@dataclass
class Conversation(Serializable):
    """
    Text chat conversation with a character.

    NOTE: Depends on character models to be loaded to be serializable.

    Attributes
    ----------
    character
        Character representing AI agent
    messages
        List of messages
    """

    character: Character
    messages: list[ConversationMessage]

    def add(self, role: str, content: str) -> ConversationMessage:
        """
        Helper function to add new conversation messages.
        
        Parameters
        ----------
        role
            Conversation role enumeration name
        content
            Text content
        """

        convo_msg = ConversationMessage(
            ConversationRole[role.upper()], content, time()
        )
        self.messages.append(convo_msg)

        return convo_msg
    
    def serialize(self) -> JSONContent:
        return {
            "character": self.character.ui_name,
            "messages": [message.serialize() for message in self.messages]
        }
    
    @classmethod
    def deserialize(cls, data: JSONContent) -> "Conversation":
        character = None
        for char in shared.characters:
            if char.ui_name == data["character"]:
                character = char
                break

        if character is None:
            log.fatal(f"Character <fg.yellow>{data['character']}</> is not loaded.")
            raise ValueError(f"Character {data['character']} is not loaded.")

        return cls(
            character=character,
            messages=[ConversationMessage.deserialize(message) for message in data["messages"]]
        )


@dataclass
class GenerationRequest:
    """
    Text generation request data.
    
    Attributes
    ----------
    convo
        Conversation to use as the prompt
    mode
        Generation mode

        Doesn't affect the generation itself, it's passed down to signals
    """
    convo: Conversation
    mode: str